/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CRMButtons: typeof import('./src/VueComponents/CRMButtons.vue')['default']
    CRMLayout: typeof import('./src/VueComponents/CRMLayout.vue')['default']
    CustomAccordion: typeof import('./src/VueComponents/CustomComponent/customAccordion.vue')['default']
    Header: typeof import('./src/VueComponents/Header.vue')['default']
    HeroHeader: typeof import('./src/VueComponents/HeroHeader.vue')['default']
    IonAccordion: typeof import('@ionic/vue')['IonAccordion']
    IonAccordionGroup: typeof import('@ionic/vue')['IonAccordionGroup']
    IonAlert: typeof import('@ionic/vue')['IonAlert']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonCard: typeof import('@ionic/vue')['IonCard']
    IonCardContent: typeof import('@ionic/vue')['IonCardContent']
    IonCardHeader: typeof import('@ionic/vue')['IonCardHeader']
    IonCardSubtitle: typeof import('@ionic/vue')['IonCardSubtitle']
    IonCardTitle: typeof import('@ionic/vue')['IonCardTitle']
    IonCol: typeof import('@ionic/vue')['IonCol']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonFooter: typeof import('@ionic/vue')['IonFooter']
    IonGrid: typeof import('@ionic/vue')['IonGrid']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonMenu: typeof import('@ionic/vue')['IonMenu']
    IonMenuButton: typeof import('@ionic/vue')['IonMenuButton']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRow: typeof import('@ionic/vue')['IonRow']
    IonSearchbar: typeof import('@ionic/vue')['IonSearchbar']
    IonSplitPane: typeof import('@ionic/vue')['IonSplitPane']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/VueComponents/Sidebar.vue')['default']
    TenentLayout: typeof import('./src/VueComponents/TenentLayout.vue')['default']
    Test: typeof import('./src/VueComponents/Test.vue')['default']
  }
}
